### ISSUE TITLE
Race Condition When Writing Filter to Disk

### ISSUE THREAD

**Issue by naftulikay** [mtchavez/cuckoo#21]
I have something similar to this:

```golang
package main

import (
  "github.com/mtchavez/cuckoo"
  "sync"
)

type struct Persister {
  filter cuckoo.Filter
  fileName string
  lock sync.Mutex
}

func (p *Persister) Save() {
  p.lock.Lock()
  defer p.lock.Unlock()

  p.filter.Save(p.fileName)
}
```

I have multiple goroutines attempting to call `Persister.Save()` after modifications to ensure that changes get persisted.

Since when `Filter.Save()` returns, there seems to be no guarantee that the data is written to disk, it appears that these goroutines truncate file writes for each other and everything descends into madness with the size of my `Filter` growing in memory within the program, but flapping in terms of disk file size: I see sizes of 29, 2MiB, 4MiB, and other values between, as these writes appear to be overlapping each other.

I'm not sure what the solution would be at the API level, but providing some way to guarantee consistency would be really helpful. For now, I have refactored my code to offset writes by consistent time periods using `time.Ticker`.

**Comment by mtchavez** [comment]
Interesting. I will look into the issue. If you have any more information that could help debug that would be useful. One question I have is how large are your persisted filters on disk? Is it up to 4MiB?

**Comment by naftulikay** [comment]
They're around 4-10MiB.

Simply have a routine which writes the filter to disk in a for loop with a mutex, and observe the filesize.

**Comment by mtchavez** [comment]
Was definitely seeing some weird behavior. Want to try out the latest code in the master branch to see if this fixes the issue you are seeing before I tag a release?

**Comment by naftulikay** [comment]
Ah, I see. Looks good to me. I don't have access to the underlying code any more, but the solution makes sense. Since the file handles were closed either never or by the GC, there must have been a lot of stale data flowing undeterministically.

**Comment by mtchavez** [comment]
Great. Going to close this out then.
